name: Deploy HospitalRun Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build the app
        run: |
          npm run build
      - name: Deploy the app
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build
